---
title: "About Stella Keck"
output: 
  html_document:
      toc: true
      toc_float: true
---

<br>

#### MPH Candidate in Environmental Health Sciences at Columbia University | Climate Change Activist | Traveler 
<br>

<br>

### Education:
<b>Columbia University Mailman School of Public Health, Department of Environmental Health Sciences</b>
<br>
Climate and Health Certificate
<br>
MPH Expected May 2019
<br><br>
<b>Rice University</b>
<br>
Bachelor of Science in Biochemistry and Cell Biology
<br>
Awarded May 2015

<br>

### About:
I am currently pursuing my MPH at Mailman School of Public Health at Columbia University in the Environmental Health Sciences department. My main interest is in adaptation and mitigation strategies to reduce the negative health impacts of climate change. Specifically, I'm interested in strategies to increase water quality and availability and reduce food insecurity domestically and internationally. I am very interested in geospatial effects of climate change and forced migration. I hope to continue working with GIS mapping and spatial data analysis within environmental topics. 

I am currently interning at the NYC Department of Health and Mental Hygiene where I work in the GIS Center fulfilling map requests and increasing my spatial analysis skills in R and ArcGIS. I am also the Departmental TA for the Environmental Health Sciences Department at Columbia University's Mailman School of Public Health where I mentor 18 first year MPH students and provide administrative assistance.

I'm also currently finishing up conducting qualitative research with Dr. Joyce Klein-Rosenthal on childhood lead poisoning from lead-based paint across the U.S. This work is sponsored by the Earth Institute at Columbia University. My past experiences include working as a software tester for Epic Systems for two years and as an undergraduate researcher in multiple wet labs. 

<br>

### Skills
<b>Technical:</b>
<br>
R, ArcGIS, MySQL, QGIS, STATA, SAS, Python, Microsoft Office Suite and Access, GeoDa, VensimPLE, EPIC (EMR)
<br>
<b>Data Analysis:</b>
<br>
Spatial Analysis and Visualization, Categorical Analysis, Logistic Regression, Multiple Variable Linear Regression, Correlation
<br>
<b>Scientific:</b>
<br>
Cytotoxicity and chromosome damage assays, immunofluorescence techniques, wet and bench chemistry
<br>
<b>Other:</b>
<br>
Social Media Networking (Instagram, Facebook, LinkedIn), Doodle, Survey Monkey, Mailchimp, Prezi
<br>